# VAR (Vector Auto Regression)
### 참고 블로그
* https://www.analyticsvidhya.com/blog/2018/09/multivariate-time-series-guide-forecasting-modeling-python-codes/
* https://www.machinelearningplus.com/time-series/vector-autoregression-examples-python/

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

# 데이터셋 로드

In [2]:
# load dataset
df = pd.read_csv('final_merged_cali.csv', header=0, index_col=0)
df= df.fillna(df.mean())
df['date_time'] = pd.to_datetime(df.date_time , format = '%Y-%m-%d')
data = df.drop(['date_time'], axis=1)
data.index = df.date_time
data.drop(["Population"], axis=1, inplace=True)
data.astype(float)
# values = data.values

            Quantity   maxtempC   mintempC  FeelsLikeC   avgtempC  month
date_time
2020-07-02       1.0  32.000000  18.000000   25.000000  25.000000    7.0
2020-07-09       2.0  37.000000  19.000000   29.000000  28.000000    7.0
2020-07-21       1.0  38.000000  22.000000   31.000000  30.000000    7.0
2020-08-30       1.0  34.000000  19.000000   27.000000  26.000000    8.0
2020-09-12       1.0  34.000000  19.000000   27.000000  26.000000    9.0
2020-10-15       1.0  33.000000  15.000000   25.000000  24.000000   10.0
2020-10-17       1.0  33.000000  16.000000   25.000000  24.000000   10.0
2020-10-19       1.0  32.000000  15.000000   24.000000  23.000000   10.0
2020-10-27       1.0  19.000000   4.000000   12.000000  11.000000   10.0
2020-11-13       3.0  17.000000   4.000000    9.000000  10.000000   11.0
2020-11-18       1.0  19.000000  11.000000   13.000000  15.000000   11.0
2020-11-21       1.0  20.000000   7.000000   13.000000  13.000000   11.0
2020-12-20       1.0  16.000000   1.000000    8.000000   8.000000   12.0
2020-12-23       1.0  15.000000   3.000000    8.000000   9.000000   12.0
2020-12-29       2.0  11.000000   2.000000    4.000000   6.000000   12.0
2021-01-04       1.0  16.000000   6.000000    9.000000  11.000000    1.0
2021-01-05       1.0  15.000000   7.000000    9.000000  11.000000    1.0
2021-01-14       2.0  19.000000   8.000000   13.000000  13.000000    1.0
2021-01-15       1.0  20.000000  10.000000   14.000000  15.000000    1.0
2021-01-22       1.0  12.000000   7.000000    7.000000   9.000000    1.0
2021-01-27       1.0   7.000000   0.000000    2.000000   3.000000    1.0
2021-01-28       1.0   7.000000   3.000000    3.000000   5.000000    1.0
2021-02-19       1.0  15.000000   5.000000    9.000000  10.000000    2.0
2021-02-22       1.0  17.000000   7.000000   11.000000  12.000000    2.0
2021-02-25       1.0  12.000000   6.000000    8.000000   9.000000    2.0
2021-02-26       1.0  16.000000   5.000000   10.000000  10.000000    2.0
2021-03-01       1.0  14.000000   5.000000    9.000000   9.000000    3.0
2021-03-04       1.0  16.000000   5.000000    9.000000  10.000000    3.0
2021-03-07       1.0  17.000000   7.000000   11.000000  12.000000    3.0
2021-03-14       2.0  17.000000   5.000000    9.000000  11.000000    3.0
2021-03-16       1.0  12.000000   1.000000    3.000000   6.000000    3.0
2021-03-23       1.0  14.000000   7.000000    8.000000  10.000000    3.0
2021-03-24       1.0  17.000000   6.000000   10.000000  11.000000    3.0
2021-03-26       1.0  17.000000   7.000000   12.000000  12.000000    3.0
2021-04-01       1.0  24.000000  13.000000   18.000000  18.000000    4.0
2021-04-02       1.0  27.000000  15.000000   21.000000  21.000000    4.0
2021-04-04       1.0  28.000000  15.000000   22.000000  21.000000    4.0
2021-04-10       1.0  24.000000  11.000000   17.000000  17.000000    4.0
2021-04-16       1.0  23.000000  11.000000   17.000000  17.000000    4.0
2021-04-18       1.0  25.000000  14.000000   20.000000  19.000000    4.0
2021-04-25       1.0  15.000000   9.000000   10.000000  12.000000    4.0
2021-05-01       1.0  28.000000  19.000000   23.000000  23.000000    5.0
2021-05-04       1.0  29.000000  17.000000   23.000000  23.000000    5.0
2021-05-13       1.0  32.000000  19.000000   25.000000  25.000000    5.0
2021-05-14       1.0  31.000000  18.000000   25.000000  24.000000    5.0
2021-05-19       1.0  26.000000  14.000000   20.000000  20.000000    5.0
2021-05-24       1.0  29.000000  14.000000   22.000000  21.000000    5.0
2021-05-29       1.0  30.000000  17.000000   24.000000  23.000000    5.0
2021-06-04       1.0  35.000000  21.000000   29.000000  28.000000    6.0
2021-06-12       2.0  33.000000  15.000000   25.000000  24.000000    6.0
2021-06-13       2.0  35.000000  19.000000   27.000000  27.000000    6.0
2021-06-17       2.0  40.000000  25.000000   33.000000  32.000000    6.0
2021-06-22       1.0  33.000000  21.000000   27.000000  27.000000    6.0
2021-06-25       1.0  34.000000  19.000000   27.000000  26.000000    6.0
2021-06-26       4.0  23.166667  11.259259   16.685185  16.944444    6.0
2021-06-27       1.0  23.166667  11.259259   16.685185  16.944444    6.0
2021-06-28       2.0  23.166667  11.259259   16.685185  16.944444    6.0

In [3]:
data.tail()

            Quantity   maxtempC   mintempC  FeelsLikeC   avgtempC  month
date_time
2021-06-22         1  33.000000  21.000000   27.000000  27.000000      6
2021-06-25         1  34.000000  19.000000   27.000000  26.000000      6
2021-06-26         4  23.166667  11.259259   16.685185  16.944444      6
2021-06-27         1  23.166667  11.259259   16.685185  16.944444      6
2021-06-28         2  23.166667  11.259259   16.685185  16.944444      6

# 훈련 및 검증 데이터 셋 분리 및 VAR 모델 생성

In [12]:
#creating the train and validation set
train = data[:int(0.8*(len(data)))]
valid = data[int(0.8*(len(data))):]


#fit the model
from statsmodels.tsa.vector_ar.var_model import VAR

model = VAR(endog=train)
model_fit = model.fit()

# make prediction on validation
prediction = model_fit.forecast(model_fit.y, steps=len(valid))

C:\Users\PC\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:216: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  warnings.warn('A date index has been provided, but it has no'

In [13]:
#converting predictions to dataframe
from math import sqrt
from sklearn.metrics import mean_squared_error
cols = data.columns
print(cols)
pred = pd.DataFrame(index=range(0,len(prediction)),columns=[cols])

for j in range(0,6):
    for i in range(0, len(prediction)):
       pred.iloc[i][j] = prediction[i][j]

pred.head()

Index(['Quantity', 'maxtempC', 'mintempC', 'FeelsLikeC', 'avgtempC', 'month'], dtype='object')

  Quantity maxtempC mintempC FeelsLikeC avgtempC    month
0  0.95743  29.1589  15.5433    22.8274  22.0761  5.56861
1  1.12812  27.6349  14.0062    21.0274  20.5024  6.30968
2  1.12227  26.2691  12.9926    19.5689  19.3409  6.62048
3  1.14563  25.2727  12.1986    18.5206   18.434  6.76664
4  1.14961   24.399  11.5583     17.645  17.6809  6.78299

In [9]:
#check rmse
import numpy as np

for i in cols:
    print(pred[i], valid[i])
    # print('rmse value for', i, 'is : ',mean_squared_error(pred[i], valid[i]))

   Quantity maxtempC mintempC FeelsLikeC avgtempC    month
0   0.95743  29.1589  15.5433    22.8274  22.0761  5.56861
1   1.12812  27.6349  14.0062    21.0274  20.5024  6.30968
2   1.12227  26.2691  12.9926    19.5689  19.3409  6.62048
3   1.14563  25.2727  12.1986    18.5206   18.434  6.76664
4   1.14961   24.399  11.5583     17.645  17.6809  6.78299
5   1.15731  23.6813  11.0494    16.9398  17.0676  6.73039
6   1.15978  23.0847  10.6527    16.3675  16.5732  6.62613
7   1.16092  22.5993  10.3468    15.9119  16.1791  6.49227
8   1.16018  22.2045   10.113    15.5503  15.8665  6.34243
9   1.15858  21.8857  9.93601    15.2654  15.6202   6.1877
10  1.15634  21.6293  9.80376    15.0425  15.4274  6.03523
11   1.1538  21.4244  9.70642    14.8693  15.2776  5.88993

TypeError: only integer scalar arrays can be converted to a scalar index